Description: >

    This template deploys a VPC with public and private subnets across two Availability
    Zones. It deploys an Internet Gateway, with a default route on the public subnets. 
    It deploys a pair of NAT Gateways (one in each AZ), and default routes for them in
    the private subnets.

    It then creates an ECS cluster to deploy Fargate tasks into.

    Finally, it deploys a pair of example ECS services from containers published in 
    Amazon EC2 Container Registry (Amazon ECR). It can optionally deploy additional
    copies of the 'worker' service to demonstrate the service discovery service.

    Last Modified: 28th September 2018
    Author: Paul Lewis <pjlewis@amazon.co.uk>

Parameters:

    DeployAdditionalServices:
        Description: Choose whether to deploy additional copies of the 'worker' service or not
        Type: String
        AllowedValues:
            - true
            - false
        Default: false

Conditions:

    AdditionalServices:
        !Equals  [ !Ref DeployAdditionalServices, true ]

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/infrastructure/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                VpcCIDR:            10.20.0.0/16
                PublicSubnet1CIDR:  10.20.8.0/21
                PublicSubnet2CIDR:  10.20.16.0/21
                PrivateSubnet1CIDR: 10.20.24.0/21
                PrivateSubnet2CIDR: 10.20.32.0/21

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/infrastructure/security-groups.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/infrastructure/load-balancers.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/infrastructure/ecs-cluster.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName

    PrivateDnsNameSpace:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/infrastructure/service-discovery.yaml
            Parameters:
                Name: corp
                VPC: !GetAtt VPC.Outputs.VPC

    BackendService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/backend/service.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 2
                ExecutionRole: !GetAtt ECS.Outputs.ExecutionRole
                Listener: !GetAtt ALB.Outputs.Listener
                LoadBalancer: !GetAtt ALB.Outputs.LoadBalancer
                PrivateDnsNamespace: !GetAtt PrivateDnsNameSpace.Outputs.PrivateDnsNamespace
                SecurityGroups: !GetAtt SecurityGroups.Outputs.FargateBackendSecurityGroup
                Subnet1: !GetAtt VPC.Outputs.PrivateSubnet1
                Subnet2: !GetAtt VPC.Outputs.PrivateSubnet2
                VPC: !GetAtt VPC.Outputs.VPC

    WorkerService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/workers/service.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 2
                ExecutionRole: !GetAtt ECS.Outputs.ExecutionRole
                PrivateDnsNamespace: !GetAtt PrivateDnsNameSpace.Outputs.PrivateDnsNamespace
                SecurityGroups: !GetAtt SecurityGroups.Outputs.FargateWorkerSecurityGroup
                ServiceName: worker
                Subnet1: !GetAtt VPC.Outputs.PrivateSubnet1
                Subnet2: !GetAtt VPC.Outputs.PrivateSubnet2
                VPC: !GetAtt VPC.Outputs.VPC

    FeedService:
        Type: AWS::CloudFormation::Stack
        Condition: AdditionalServices
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/workers/service.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 3
                ExecutionRole: !GetAtt ECS.Outputs.ExecutionRole
                PrivateDnsNamespace: !GetAtt PrivateDnsNameSpace.Outputs.PrivateDnsNamespace
                SecurityGroups: !GetAtt SecurityGroups.Outputs.FargateWorkerSecurityGroup
                ServiceName: feed
                Subnet1: !GetAtt VPC.Outputs.PrivateSubnet1
                Subnet2: !GetAtt VPC.Outputs.PrivateSubnet2
                VPC: !GetAtt VPC.Outputs.VPC

    AuthService:
        Type: AWS::CloudFormation::Stack
        Condition: AdditionalServices
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/workers/service.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 2
                ExecutionRole: !GetAtt ECS.Outputs.ExecutionRole
                PrivateDnsNamespace: !GetAtt PrivateDnsNameSpace.Outputs.PrivateDnsNamespace
                SecurityGroups: !GetAtt SecurityGroups.Outputs.FargateWorkerSecurityGroup
                ServiceName: auth
                Subnet1: !GetAtt VPC.Outputs.PrivateSubnet1
                Subnet2: !GetAtt VPC.Outputs.PrivateSubnet2
                VPC: !GetAtt VPC.Outputs.VPC

    MessengerService:
        Type: AWS::CloudFormation::Stack
        Condition: AdditionalServices
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/workers/service.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 3
                ExecutionRole: !GetAtt ECS.Outputs.ExecutionRole
                PrivateDnsNamespace: !GetAtt PrivateDnsNameSpace.Outputs.PrivateDnsNamespace
                SecurityGroups: !GetAtt SecurityGroups.Outputs.FargateWorkerSecurityGroup
                ServiceName: messenger
                Subnet1: !GetAtt VPC.Outputs.PrivateSubnet1
                Subnet2: !GetAtt VPC.Outputs.PrivateSubnet2
                VPC: !GetAtt VPC.Outputs.VPC

    UserService:
        Type: AWS::CloudFormation::Stack
        Condition: AdditionalServices
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/workers/service.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 4
                ExecutionRole: !GetAtt ECS.Outputs.ExecutionRole
                PrivateDnsNamespace: !GetAtt PrivateDnsNameSpace.Outputs.PrivateDnsNamespace
                SecurityGroups: !GetAtt SecurityGroups.Outputs.FargateWorkerSecurityGroup
                ServiceName: user
                Subnet1: !GetAtt VPC.Outputs.PrivateSubnet1
                Subnet2: !GetAtt VPC.Outputs.PrivateSubnet2
                VPC: !GetAtt VPC.Outputs.VPC

    TimelineService:
        Type: AWS::CloudFormation::Stack
        Condition: AdditionalServices
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/pjlewis-aws-ecs-service-discovery-demo/workers/service.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 3
                ExecutionRole: !GetAtt ECS.Outputs.ExecutionRole
                PrivateDnsNamespace: !GetAtt PrivateDnsNameSpace.Outputs.PrivateDnsNamespace
                SecurityGroups: !GetAtt SecurityGroups.Outputs.FargateWorkerSecurityGroup
                ServiceName: timeline
                Subnet1: !GetAtt VPC.Outputs.PrivateSubnet1
                Subnet2: !GetAtt VPC.Outputs.PrivateSubnet2
                VPC: !GetAtt VPC.Outputs.VPC

Outputs:

    DemoServiceUrl: 
        Description: The URL endpoint for the demo service
        Value: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "/" ]]